using Microsoft.EntityFrameworkCore;
using RentalHub.Infrastructure.Data;

namespace RentalHub.API.Services;

public sealed class DatabaseInitializerHostedService : IHostedService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<DatabaseInitializerHostedService> _logger;
    private readonly IConfiguration _configuration;

    public DatabaseInitializerHostedService(
        IServiceProvider serviceProvider,
        ILogger<DatabaseInitializerHostedService> logger,
        IConfiguration configuration)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
        _configuration = configuration;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        var ensureCreated = _configuration.GetValue("Database:EnsureCreatedOnStartup", true);
        if (!ensureCreated)
        {
            return;
        }

        try
        {
            using var scope = _serviceProvider.CreateScope();
            var dbContext = scope.ServiceProvider.GetRequiredService<RentalHubDbContext>();
            await dbContext.Database.EnsureCreatedAsync(cancellationToken);
            await EnsureSprint2TablesAsync(dbContext, cancellationToken);
            _logger.LogInformation("RentalHub database schema is ready.");
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not initialize RentalHub database schema. The API will continue running.");
        }
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    private static async Task EnsureSprint2TablesAsync(RentalHubDbContext dbContext, CancellationToken cancellationToken)
    {
        await dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "Proprietarios" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "TenantId" integer NOT NULL,
                "Nome" character varying(180) NOT NULL,
                "Documento" character varying(32) NOT NULL,
                "Telefone" character varying(40),
                "Email" character varying(180),
                "DadosBancarios" character varying(500),
                "Observacoes" character varying(1000),
                "Ativo" boolean NOT NULL,
                "DataCriacao" timestamp with time zone NOT NULL,
                "DataAtualizacao" timestamp with time zone,
                CONSTRAINT "PK_Proprietarios" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_Proprietarios_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Proprietarios_TenantId_Documento" ON "Proprietarios" ("TenantId", "Documento");
            CREATE INDEX IF NOT EXISTS "IX_Proprietarios_TenantId_Nome" ON "Proprietarios" ("TenantId", "Nome");

            CREATE TABLE IF NOT EXISTS "Imoveis" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "TenantId" integer NOT NULL,
                "ProprietarioId" integer NOT NULL,
                "Nome" character varying(180) NOT NULL,
                "CodigoInterno" character varying(60) NOT NULL,
                "Descricao" character varying(2000),
                "Endereco" character varying(260),
                "Cidade" character varying(120),
                "Estado" character varying(2),
                "Cep" character varying(12),
                "QuantidadeHospedes" integer NOT NULL,
                "QuantidadeQuartos" integer NOT NULL,
                "QuantidadeBanheiros" integer NOT NULL,
                "Status" integer NOT NULL,
                "DataCriacao" timestamp with time zone NOT NULL,
                "DataAtualizacao" timestamp with time zone,
                CONSTRAINT "PK_Imoveis" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_Imoveis_Proprietarios_ProprietarioId" FOREIGN KEY ("ProprietarioId") REFERENCES "Proprietarios" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_Imoveis_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Imoveis_TenantId_CodigoInterno" ON "Imoveis" ("TenantId", "CodigoInterno");
            CREATE INDEX IF NOT EXISTS "IX_Imoveis_TenantId_Nome" ON "Imoveis" ("TenantId", "Nome");
            CREATE INDEX IF NOT EXISTS "IX_Imoveis_ProprietarioId" ON "Imoveis" ("ProprietarioId");

            CREATE TABLE IF NOT EXISTS "ImovelComodidades" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "TenantId" integer NOT NULL,
                "ImovelId" integer NOT NULL,
                "Nome" character varying(90) NOT NULL,
                CONSTRAINT "PK_ImovelComodidades" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ImovelComodidades_Imoveis_ImovelId" FOREIGN KEY ("ImovelId") REFERENCES "Imoveis" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_ImovelComodidades_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ImovelComodidades_TenantId_ImovelId_Nome" ON "ImovelComodidades" ("TenantId", "ImovelId", "Nome");
            CREATE INDEX IF NOT EXISTS "IX_ImovelComodidades_ImovelId" ON "ImovelComodidades" ("ImovelId");

            CREATE TABLE IF NOT EXISTS "ImovelFotos" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "TenantId" integer NOT NULL,
                "ImovelId" integer NOT NULL,
                "Url" character varying(800) NOT NULL,
                "Descricao" character varying(200),
                "Ordem" integer NOT NULL,
                "Principal" boolean NOT NULL,
                CONSTRAINT "PK_ImovelFotos" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ImovelFotos_Imoveis_ImovelId" FOREIGN KEY ("ImovelId") REFERENCES "Imoveis" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_ImovelFotos_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
            );

            CREATE INDEX IF NOT EXISTS "IX_ImovelFotos_TenantId_ImovelId_Ordem" ON "ImovelFotos" ("TenantId", "ImovelId", "Ordem");
            CREATE INDEX IF NOT EXISTS "IX_ImovelFotos_ImovelId" ON "ImovelFotos" ("ImovelId");

            CREATE TABLE IF NOT EXISTS "Hospedes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "TenantId" integer NOT NULL,
                "Nome" character varying(180) NOT NULL,
                "Email" character varying(180),
                "Telefone" character varying(40),
                "Documento" character varying(40),
                "Nacionalidade" character varying(80),
                "Observacoes" character varying(1000),
                "Ativo" boolean NOT NULL,
                "DataCriacao" timestamp with time zone NOT NULL,
                "DataAtualizacao" timestamp with time zone,
                CONSTRAINT "PK_Hospedes" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_Hospedes_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
            );

            CREATE INDEX IF NOT EXISTS "IX_Hospedes_TenantId_Nome" ON "Hospedes" ("TenantId", "Nome");
            CREATE INDEX IF NOT EXISTS "IX_Hospedes_TenantId_Email" ON "Hospedes" ("TenantId", "Email");
            """,
            cancellationToken);
    }
}
